Repository jenkinsci/purge-build-queue-plugin, pull requests merged in 2022-02, with the labels that each got.

#5 Provide german translation
  .github/dependabot.yml
  src/main/java/io/jenkins/plugins/PurgeBuildQueueAction.java
  src/main/resources/io/jenkins/plugins/Messages.properties
  src/main/resources/io/jenkins/plugins/Messages_de.properties
  src/main/resources/io/jenkins/plugins/PurgeBuildQueueAction/index.jelly
  src/main/resources/io/jenkins/plugins/PurgeBuildQueueAction/index_de.properties
Labels: feature

#6 Fix CD to not publish "rc" artifacts
  .mvn/maven.config
  pom.xml
Labels: bug

#9 Update "plugin" to 4.36 and setup security scanning
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/jenkins-security-scan.yml
  .github/workflows/release-drafter.yml
  pom.xml
Labels: enhancement

#10 Display icon only with ADMINISTER permission
  src/main/java/io/jenkins/plugins/PurgeBuildQueueAction.java
Labels: feature
